### ISSUE TITLE
Some minor problems with supertux and tuxmath

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode-world#44]

**Comment by m-stein** [comment]
@nfeske: In addition to the HW RPI timing fixes.

**Comment by nfeske** [comment]
It seems that your branch is based on an older version of the master branch. E.g., the changed location of the supertux sources is already fixed in https://github.com/genodelabs/genode-world/commit/1cb50bb41d06fed065aafa0de9bece4bf2385704 Could you please rebase your branch on the current version of the master branch?

**Comment by m-stein** [comment]
@nfeske Thanks for the hint. I've updated the branch.

**Comment by nfeske** [comment]
Thank you. I merged both commits to master.
